### ISSUE TITLE
workflow title display issue in the holding pen

### ISSUE THREAD

**Issue by monaawi** [inspirehep/inspirehep#1410] opened 2020-10-08 10:33 UTC
https://inspirehep.net/holdingpen/2546221
Title is not displayed for some workflows even though it is in the metadata.
```
Error: [$sanitize:badparse] The sanitizer was unable to parse the following block of html: <z<3.0$
```

**Comment by harunurhan** [comment] 2020-10-14 11:43
Isn't this #1405 ?

**Comment by drjova** [comment] 2020-10-21 12:05
duplicate of https://github.com/inspirehep/inspirehep/issues/1405

**Closed by drjova** 2020-10-21 12:05 UTC
Labels: type: bug
