### ISSUE TITLE
Literature submission for eprint `2004.10710`

### ISSUE THREAD

**Issue by drjova** [inspirehep/inspirehep#1403] opened 2020-10-07 12:22 UTC
When you try to submit `2004.10710` eprint, clicking the `Submit` button it will just scroll you on the top of the page without any error.

**Comment by harunurhan** [comment] 2020-10-14 13:19
Looks like this because `document_type: null` in `/api/literature/import/2004.10710`

which is caused by a bug in `inspire-merger` or `json-merger`.

https://github.com/inspirehep/inspirehep/blob/fb192a008a15b3b763a005d409790e80c8920e20/backend/inspirehep/records/api/literature.py#L543
- `article` which data from `arxiv` has `document_type: ["conference paper"]`
- `crossref_data` has `document_type: ["article"]`
- however `merged` has  `document_type: "conference paper"` which is not even valid according to the literature schema. It has to an array.

https://github.com/inspirehep/inspirehep/blob/fb192a008a15b3b763a005d409790e80c8920e20/backend/inspirehep/submissions/marshmallow/literature.py#L80
Since we pick the first `document_type` (not an array in this case) as the `document_type` in form data, it becomes `null`.

**Closed** 2020-10-29 11:53 UTC
Labels: type: bug
