### ISSUE TITLE
Improve ambiguous JHEP/JCAP reference matching

### ISSUE THREAD

**Issue by michamos** [inspirehep/inspirehep#1688] opened 2021-02-01 16:45 UTC
The JHEP/JCAP reference display they recommend is really bad and ambiguous. @ksachs implemented a [bibcheck plugin](https://github.com/inspirehep/inspire/blob/master/bibcheck/plugins/jcap_jhep_pages.py) on legacy to "fix" the references affected by this issue (and some others?) to make them non-ambiguous. We need to implement similar logic on `hep`, but we can probably perform smarter reference matching instead of needing to rewrite references.

**Comment by ksachs** [comment] 2021-02-09 11:57
here is an [idea](https://docs.google.com/document/d/10H1johW1j3NCm-dCzSuZEKGr412eWFeVtbCmeEr9m-Y)
and some [pseudo-code](https://docs.google.com/presentation/d/1sPuZBmO5hYv8A2j_wfvz-Rbu79GDqq1gLoYx6ehuRUs/edit?usp=sharing) (not final) for the automatic part

**Comment by michamos** [comment] 2021-02-09 11:58
Thanks @ksachs, that's very instructive.

**Comment by ksachs** [comment] 2021-02-09 12:00
and it's [this bibcheck plugin](https://github.com/inspirehep/inspire/blob/master/bibcheck/plugins/fix_ref_jhep_volume.py)

**Comment by ksachs** [comment] 2021-04-15 16:28
Some [pseudo code](https://docs.google.com/presentation/d/18QwoI0pbXu8M03nfDUO9TzisOFdI9h6FlS02BAQInsE/edit#slide=id.p) to replace only the automatic part of the bibcheck

**Comment by ksachs** [comment] 2021-04-20 06:50
Statistics since 2020-05-29 (don't know if there are older log files around)
bibsched_task_777539

automatically fixed, confirmed via
DOI: 4463	
RepNo: 6897
	
PubNote: 920	
Author: 6497	
Collaboration: 619	
Title: 224

**Comment by ksachs** [comment] 2021-04-20 06:54
[bibsched_task_777539.PubNote.log](https://github.com/inspirehep/inspirehep/files/6341233/bibsched_task_777539.PubNote.log)
Examples of references fixed by re-parsing the raw-reference.
Mostly PTEP, esp. since Review of Particle Physics is PTEP,2020,083C01 which is highly cited and almost always wrong by refextract

**Comment by karolina-siemieniuk-morawska** [comment] 2023-09-20 08:42
@michamos moved the issue to cern-sis/issues-inspire (https://github.com/cern-sis/issues-inspire/issues/391)

**Closed by karolina-siemieniuk-morawska** 2023-09-20 08:42 UTC
Labels: type: spike, status: ready for refinement, priority: high

**Comment by michamos** [comment] 2023-09-20 10:25
oh ok, hadn't realized, all good then :sweat_smile:
