### ISSUE TITLE
Continous migration is failing

### ISSUE THREAD

**Issue by pazembrz** [inspirehep/inspirehep#1742] opened 2021-03-04 11:18 UTC
https://sentry.inspirehep.net/inspire-prod/hep/issues/27072/?query=is%3Aunresolved

'list' object has no attribute 'decode'  in inspirehep/migrator/tasks.py in migrate_recids_from_mirror at line 273

**Comment by pazembrz** [comment] 2021-03-04 13:07
Going further with source of the error:
```Python

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/celery/backends/asynchronous.py", line 166, in add_pending_result
    self._maybe_resolve_from_buffer(result)
  File "/usr/local/lib/python3.6/site-packages/celery/backends/asynchronous.py", line 172, in _maybe_resolve_from_buffer
    result._maybe_set_cache(self._pending_messages.take(result.id))
  File "/usr/local/lib/python3.6/site-packages/celery/utils/collections.py", line 884, in take
    raise self.Empty()
queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 412, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/flask_celeryext/app.py", line 84, in __call__
    return Task.__call__(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 704, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/sentry_sdk/integrations/celery.py", line 132, in _inner
    reraise(*exc_info)
  File "/usr/local/lib/python3.6/site-packages/sentry_sdk/_compat.py", line 54, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/sentry_sdk/integrations/celery.py", line 127, in _inner
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/celery/app/autoretry.py", line 35, in run
    return task._orig_run(*args, **kwargs)
  File "/opt/inspire/inspirehep/migrator/tasks.py", line 273, in migrate_recids_from_mirror
    chord_task = chord(header)(callback.on_error(fail_info.s()))
  File "/usr/local/lib/python3.6/site-packages/celery/canvas.py", line 1318, in __call__
    return self.apply_async((), {'body': body} if body else {}, **options)
  File "/usr/local/lib/python3.6/site-packages/celery/canvas.py", line 1371, in apply_async
    return self.run(tasks, body, args, task_id=task_id, **merged_options)
  File "/usr/local/lib/python3.6/site-packages/celery/canvas.py", line 1420, in run
    header_result = header.freeze(group_id=group_id, chord=body, root_id=root_id)
  File "/usr/local/lib/python3.6/site-packages/celery/canvas.py", line 1223, in freeze
    return self.app.GroupResult(gid, results)
  File "/usr/local/lib/python3.6/site-packages/celery/result.py", line 920, in __init__
    ResultSet.__init__(self, results, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/celery/result.py", line 547, in __init__
    self._on_full = ready_barrier or barrier(results)
  File "/usr/local/lib/python3.6/site-packages/vine/synchronization.py", line 57, in __init__
    [self.add_noincr(p) for p in promises or []]
  File "/usr/local/lib/python3.6/site-packages/vine/synchronization.py", line 57, in <listcomp>
    [self.add_noincr(p) for p in promises or []]
  File "/usr/local/lib/python3.6/site-packages/vine/synchronization.py", line 82, in add_noincr
    p.then(self)
  File "/usr/local/lib/python3.6/site-packages/celery/result.py", line 121, in then
    self.backend.add_pending_result(self, weak=weak)
  File "/usr/local/lib/python3.6/site-packages/celery/backends/asynchronous.py", line 168, in add_pending_result
    self._add_pending_result(result.id, result, weak=weak)
  File "/usr/local/lib/python3.6/site-packages/celery/backends/asynchronous.py", line 178, in _add_pending_result
    self.result_consumer.consume_from(task_id)
  File "/usr/local/lib/python3.6/site-packages/celery/backends/redis.py", line 169, in consume_from
    self._consume_from(task_id)
  File "/usr/local/lib/python3.6/site-packages/celery/backends/redis.py", line 176, in _consume_from
    self._pubsub.subscribe(key)
  File "/usr/local/lib/python3.6/site-packages/redis/client.py", line 3260, in subscribe
    ret_val = self.execute_command('SUBSCRIBE', *iterkeys(new_channels))
  File "/usr/local/lib/python3.6/site-packages/redis/client.py", line 3155, in execute_command
    self._execute(connection, connection.send_command, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/redis/client.py", line 3159, in _execute
    return command(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/redis/connection.py", line 687, in send_command
    check_health=kwargs.get('check_health', True))
  File "/usr/local/lib/python3.6/site-packages/redis/connection.py", line 661, in send_packed_command
    self.check_health()
  File "/usr/local/lib/python3.6/site-packages/redis/connection.py", line 645, in check_health
    if nativestr(self.read_response()) != 'PONG':
  File "/usr/local/lib/python3.6/site-packages/redis/_compat.py", line 173, in nativestr
    return x if isinstance(x, str) else x.decode('utf-8', 'replace')
AttributeError: 'list' object has no attribute 'decode'
```

Is it Redis bug...?

**Comment by pazembrz** [comment] 2021-03-04 13:18
```Python
AttributeError: 'list' object has no attribute 'decode'
> /usr/local/lib/python3.6/site-packages/redis/_compat.py(173)nativestr()
    171 
    172     def nativestr(x):
--> 173         return x if isinstance(x, str) else x.decode('utf-8', 'replace')
    174 
    175     next = next

ipdb> ll                                                                                                                                                                                      
    172     def nativestr(x):
--> 173         return x if isinstance(x, str) else x.decode('utf-8', 'replace')
    174 

ipdb> x                                                                                                                                                                                       
[b'unsubscribe', b'celery-task-meta-d98c484b-e190-48c3-ab0d-ddd7b88aa6cd', 0]
```

**Comment by pazembrz** [comment] 2021-03-05 07:45
I tested this manually on prod worker (as only there this is happening (I cannot recreate it Locally nor on QA). Looks like it's time(?) dependent. When it fails it will fail on every call for migration (creating chords (in `migrate_recids_from_mirror`) and/or reading state of task (on `waiting_for_tasks` function) ). When it's OK then it won't fail at all no mater what. 
Might this be network dependent maybe?

**Comment by pazembrz** [comment] 2021-03-05 09:14
At the end looks like there were 5 workers which had problems with Redis connection. After restarting them error didn't  happened for last hour.

**Comment by michamos** [comment] 2021-03-05 09:52
To me this looks like some bug in the python redis client, which seems to assume that the response after the health check will be the result of the health check. Instead, here it looks like the client was previously in pubsub mode and unsubscribed, but the `unsubscribe` message was not read previously, so it's still in the redis receive buffer (or something like that, I'm not entirely sure how it works internally), and it seems like we received an `unsubscribe` message as a response to the health check. It should be possible to reproduce this bug bug going into pubsub mode, subscribing to a channel, unsubscribing, subscribing again with health checks turned on.

**Comment by michamos** [comment] 2021-03-05 10:53
I tried reproducing it locally by doing various combinations of subscribing, unsubscribe, resetting the connection, taking down redis, etc., but didn't manage to. I'll submit a bug report to `redis-py`, hopefully they'll have some idea of what's going on.

**Comment by michamos** [comment] 2021-03-05 11:02
We're on a very old version of redis: 3.3.11 from October 2019, maybe we should update to the latest version first and check whether it's still happening? I don't expect it though, as I read the full commit log and didn't see anything related, so I'll report the issue directly.

**Comment by michamos** [comment] 2021-03-05 11:23
Opened an issue in https://github.com/andymccurdy/redis-py/issues/1456

**Comment by michamos** [comment] 2021-09-06 13:01
Hasn't happened in a long time, and we're not running the continuous migration any longer, so I'm closing this.

**Closed by michamos** 2021-09-06 13:01 UTC
Labels: type: bug
